homeinsightapp/urls.py
from django.urls import path
from .views import *
from django.urls import path

app_name='homeinsightapp'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('guest/', guest, name="guest"),
    path('profiles/', ProfileList.as_view(), name="profile-list"),
    path('profiles/create/', ProfileCreate.as_view(), name="profile-create"),
    path('ajax/load-localitati/', load_localitati, name='ajax_load_localitati'),
    path('profiles/<str:profile_id>/', ProfileDetail.as_view(), name="dashboard"),
    path('profiles/<str:profile_id>/devices/', DeviceList.as_view(), name="devicelist"),
    path('profiles/<str:profile_id>/devices/<str:device_id>/', DeviceDetail.as_view(), name="device-detail"),
    path('profiles/<str:profile_id>/devices/<str:device_id>/submit_index', index_updated, name="index_updated"),
    ]

homeinsightprj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeinsightapp.urls')),
    path('accounts/', include('allauth.urls')),
]

geodata/models.py
from django.db import models
from django.urls import reverse
from django import forms
import uuid, requests, json
from datetime import timedelta, datetime


class GeodataTara(models.Model):
    id = models.BigAutoField(primary_key=True)
    surogate = models.CharField(max_length=150)
    name = models.CharField(max_length=40)

    class Meta:
        db_table = 'geodata_geodatatara'

    def __str__(self):
        return self.name

class GeodataJudet(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=125)
    abreviere = models.CharField(max_length=20)
    tara = models.ForeignKey(GeodataTara, models.DO_NOTHING)

    class Meta:
        db_table = 'geodata_geodajudet'

    def __str__(self):
        return self.name
    
class GeodataLocalitate(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=125)
    judet = models.ForeignKey(GeodataJudet, models.DO_NOTHING, blank=True, null=True)
    tara = models.ForeignKey(GeodataTara, models.DO_NOTHING, blank=True, null=True)
    latitude = models.CharField(max_length=7, blank=True, null=True)
    longitude = models.CharField(max_length=7, blank=True, null=True)

    class Meta:
        db_table = 'geodata_geodalocalitate'

    def __str__(self):
        return self.name

class GeodataStrada(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=125)
    judet = models.ForeignKey(GeodataJudet, models.DO_NOTHING)
    localitate = models.ForeignKey(GeodataLocalitate, models.DO_NOTHING)
    tara = models.ForeignKey(GeodataTara, models.DO_NOTHING)

    def __str__(self):
        return self.name

templates/base.html
{% load static %}

<html>
  <head>
    <meta name="description" content="Hello this is my first web page!." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"/>
    <link rel="stylesheet"  href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">

    <link rel="stylesheet" href="{% static 'assets/src/styles.css' %}" />

    <link rel="icon" href="{% static 'assets/login/img/app_logo_green.png' %}">
    <title>Home Insight</title>
    
  </head>
  <body>
    <header>
      <nav class="navbar">
        <div class="navbar__brand row">
             <!-- <img src="{% static 'assets/login/img/app_logo_white_circle.png' %}" alt="logo" class="brand__logo" /> -->
        </div>
             
          {% if not request.user.is_authenticated %}
          <div class="nav__item">
            <a href="{% url 'account_login' %}" class="btn btn-outline-primary btn-lg" role="button" > Sign in</a>
          </div>
          {% else %}
          <div>
              <a class="btn btn-outline-light btn-lg" role="button" href="{% url 'account_logout' %}">Logout</a>
          </div>
          {% endif %}
        </div>
      </nav>
    </header>

    {% block content %}
    
    {% endblock content %}

    <footer>
      <div class="footer__row__2">
        <div class="column__1">
          <p>FAQ</p>
          <p>Investor Relations</p>
          <p>Privacy</p>
        </div>
        <div class="column__2">
          <p>Help Centre</p>
          <p>Jobs</p>
          <p>Cookie Preferences</p>
        </div>

        <div class="column__3">
          <p>Media Centre</p>
          <p>Terms of Use</p>
          <p>Contact Us</p>
        </div>
      </div>
    </footer>

    <script src="{% static 'assets/src/index.js' %}"></script>
    <script src="{% static 'assets/login/js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

   
  </body>
</html>

templates/dashboard.html
{% extends 'profile-base.html' %} {% load static %} {% block pagetitle %}
<div class="pagetitle d-flex flex-column justify-content-center">
  <h1 class="mb-0">Dashboard</h1>
  <nav>
    <ol class="breadcrumb m-0 p-0">
      <li class="breadcrumb-item">Profile</li>
      <li class="breadcrumb-item active">Dashboard</li>
    </ol>
  </nav>
</div>

{% endblock pagetitle %} {% block content %}
<section class="section dashboard">
  <div class="row g-3 mb-3">
    <div class="col-12 col-lg-4">
      <div class="d-flex card h-100 d-flex justify-content-center">
        <div class="card-body">
          <h5 class="card-title">Daily max <span>| {{max_daily_key}}</span></h5>

          <div class="d-flex align-items-center">
            <img
              src="{% static 'assets\img\D_icon.png'  %}"
              class="card-icon d-flex align-items-center justify-content-center"
            />
            <div class="ps-3">
              <h6>{{max_daily_value}} kW⋅h</h6>
              <span class="text-muted small pt-2 ps-1">
                last recorded day
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="d-flex card h-100 d-flex justify-content-center">
        <div class="card-body">
          <h5 class="card-title">
            Monthly max <span>| {{max_monthly_key}}</span>
          </h5>

          <div class="d-flex align-items-center">
            <img
              src="{% static 'assets\img\M_icon.png'  %}"
              class="card-icon d-flex align-items-center justify-content-center"
            />
            <div class="ps-3">
              <h6>{{max_monthly_value}} kW⋅h</h6>
              <span class="text-muted small pt-2 ps-1">
                last recorded month
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="d-flex card h-100 d-flex justify-content-center">
        <div class="card-body">
          <h5 class="card-title">
            Average max <span>| {{max_yearly_key}}</span>
          </h5>

          <div class="d-flex align-items-center">
            <img
              src="{% static 'assets\img\Y_icon.png'  %}"
              class="card-icon d-flex align-items-center justify-content-center"
            />

            <div class="ps-3">
              <h6>{{max_yearly_value}} kW⋅h</h6>
              <span class="text-muted small pt-2 ps-1">
                last recorded year
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row g-3">
    <div class="col-12 col-lg-8">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">Monthly Average<span>/last year</span></h5>
          <div id="reportsChart"></div>
          <script>

            document.addEventListener("DOMContentLoaded", () => {

              new ApexCharts(document.querySelector("#reportsChart"), {
                series: [
                  {% for key, value in series.items %}
                    {
                      name: '{{ key }}',
                      data: [{% for item in value %} '{{ item }}', {% endfor %}],
                    },
                  {% endfor %}
                ],
                chart: {
                  type: 'bar',
                  height: 350,
                },
                plotOptions: {
                  bar: {
                    horizontal: false,
                    columnWidth: '55%',
                    endingShape: 'rounded',
                  },
                },
                dataLabels: {
                  enabled: false,
                },
                stroke: {
                  show: true,
                  width: 2,
                  colors: ['transparent'],
                },
                xaxis: {
                  categories: [
                    {% for time in timeseriesList %}
                      '{{ time }}',
                    {% endfor %}
                  ],
                },
                yaxis: {
                  title: {
                    text: 'kW⋅h',
                  },
                },
                fill: {
                  opacity: 1,
                },
                tooltip: {
                  y: {
                    formatter: function (val) {
                      return val + 'kW/month ';
                    },
                  },
                },
              }).render();
            });
          </script>
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="d-flex card h-100">{% include 'weather_widget.html'%}</div>
    </div>
  </div>
</section>

{% endblock content %}

templates/devicecreate.html
{% extends 'profile-base.html' %}

{% block content %}


  <div class="card">
      <div class="card-body">
        <br>
        <!-- General Form Elements -->
        <form method="POST" id="deviceForm" >
          <div class="row mb-3 ">
            <div class="col">
              {% csrf_token %}
              {{ form.as_p }}
            </div>
            <div class="col">
              <button type="submit" class="btn btn-primary"> Add device</button>
            </div>   
          </div>
        </form><!-- End General Form Elements -->
      </div>
    </div>



    
{% endblock content %}

templates/devicelist.html
{% extends 'profile-base.html' %}

{% block pagetitle %}
     <div class="pagetitle">
      <h1>Device manager</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">Profile</li>
          <li class="breadcrumb-item active">Device manager</li>
        </ol>
      </nav>

    </div>
{% endblock pagetitle %} 


{% block content %}

    <section class="section dashboard">
      <div class="row">

        <!-- Left side columns -->
        <div class="col-lg-8">
          <div class="row">

     <section class="bg-primary_black min-h-screen flex-col flex justify-center items-center">
        <div class="card">
            <div class="card-body">
    
              <br>
              <!-- General Form Elements -->
              <form method="POST" id="deviceForm" >
          
                    <label for="name">Device name: </label>
                    {% csrf_token %}
                    {{ form.name }}
       
                    <button type="submit" class="btn btn-primary mt-auto p-2"> Add device</button>   
            
              </form><!-- End General Form Elements -->
                <br> 

      

           <div class=" justify-center input_profiles ">

             <!-- Default Table -->
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Device name</th>
                    <th scope="col">Device id</th>
                    <th scope="col">Enable disable auto-track</th>

                  </tr>
                </thead>

                <tbody>
        
                  {% for device in devices %}
                  <tr>
                    <td> <a href="{% url 'homeinsightapp:device-detail' profile_id=profile.uuid device_id=device.device_id %}"> {{ device.name }} </a></td>
                    <td> {{ device.device_id}} </td>
                    <td> <div class="form-check form-switch">
                          <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                          <label class="form-check-label" for="flexSwitchCheckDefault">Enable</label>
                        </div>
                     </td>

                  </tr> 
                  {% endfor %}

                </tbody>
              </table>
        </div>
         </div>
      </div>

    </section>
    
 

    
      </div>

  </div><!-- End Left side columns -->



        <!-- Right side columns -->
        <div class="col-lg-4">

    
<div class="card">
    <div class="card-body">
        <h5 class="card-title d-flex justify-content-between">Deleted devices  <span> {% now "H:i" %} </span></h5>
         <!-- Default Table -->
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Device name</th>
                    <th scope="col">Device id</th>
                  </tr>
                </thead>

                <tbody>
                  {% for device in devices %}
                  <tr>
                    <td> {{ device.name }}</td>
                    <td> {{ device.device_id}} </td>
                  </tr> 
                  {% endfor %}
                </tbody>
              </table>

        

    </div>
</div>



        </div><!-- End Right side columns -->



      

{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <main>
      <section class="hero">
        <div class="hero__bg__image__container">
          <img src="{% static 'assets/login/img/hero2.jpg' %}"alt="BG hero image" class="hero__bg__image"  />

        </div>
        <div class="hero__bg__overlay"></div>

        <div class="hero__card">
          <h1 class="hero__title"> Smarter energy management  <br> with <span style="color:0ea5e9">Home Insight</span> </h1>
          

          <p class="hero__subtitle">
          Get a bird's eye view of your home's energy consumption, effortlessly monitor your devices, and take control of your bills. 
          </p>
          <p class="hero__description">
            Start your journey to a more sustainable future with HI today!
          </p>

          <div class="email__form__container">
            <div class="form__container">
              <input style="color: black;" type="email" class="email__input" placeholder=" " />
              <label class="email__label">Email Address</label>
            
            </div>
            <a href="{% url 'account_signup' %}" class="primary__button">
              Sign Up <i class="fal fa-chevron-right"></i>
            </a>
          </div>

          <br><br><br><br>

        </div>
        

      </section>

<section class="FAQ__list__container">
  <br><br>
        <h1 class="FAQ__heading">Frequently Asked Questions</h1>

        <div class="FAQ__list">
          <div class="FAQ__accordian">
            <button class="FAQ__title">
              Why should I track my energy usage?<i class="fal fa-plus"></i>
            </button>
            <div class="FAQ__visible">
              <p>
                Tracking your energy usage can provide several benefits, including cost savings and increased sustainability. By monitoring your energy consumption, you can identify areas where you can reduce your energy bills and save money. Additionally, understanding your energy usage patterns can help you make informed decisions about your energy consumption and take steps to reduce your carbon footprint. Overall, tracking your energy usage can help you make smarter, more sustainable energy choices.
              </p>
            </div>
          </div>
          <div class="FAQ__accordian">
            <button class="FAQ__title">
              Can the app be accessed from multiple devices?<i class="fal fa-plus"></i>
            </button>
            <div class="FAQ__visible">
              <p>
                Yes, as a web-based app, Home Insight can be accessed from multiple devices, such as smartphones, tablets, laptops, and desktops, as long as the device has an internet connection. This allows you to monitor and manage your energy consumption from anywhere, at any time.
              </p>
            </div>
          </div>
          <div class="FAQ__accordian">
            <button class="FAQ__title">
              How much does the app cost?<i class="fal fa-plus"></i>
            </button>
            <div class="FAQ__visible">
              <p>
                The Home Insight app is completely free to use. You do not need to pay any upfront costs or monthly fees to access the app and its features. By offering the app for free, our goal is to make energy management accessible to as many people as possible, regardless of their budget.
              </p>
            </div>
          </div>
          <div class="FAQ__accordian">
            <button class="FAQ__title">
              Are there any compatibility requirements for using the app?<i class="fal fa-plus"></i>
            </button>
            <div class="FAQ__visible">
              <p>
                 You do not need any special hardware or software to use the app, just a device with an internet connection and a web browser that is up-to-date. Whether you're using a laptop, tablet, or smartphone, you can access Home Insight from any device and start monitoring your energy usage and saving money.              </p>
            </div>
          </div>

         
          </div>
        </div>
        <br><br>
      </section>
    </main>

{% endblock content %}

templates/index_updated.html
{% extends 'profile-base.html' %}

{% block pagetitle %}
     <div class="pagetitle">
      <h1>{{device.name}}</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">Devices</li>
          <li class="breadcrumb-item active">DeviceIndex</li>
        </ol>
      </nav>
    </div>
{% endblock pagetitle %} 


{% block content %}

    <div>
        {{message}}
    </div>

    <a class="btn btn-primary"  href="{% url 'homeinsightapp:device-detail' profile_id=profile.uuid device_id=device.device_id %}">Back to device</a>


  {% endblock content %}

templates/profile-base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <link
      rel="icon"
      href="{% static 'assets/login/img/app_logo_green.png' %}"
    />
    <title>Home Insight</title>

    <!-- Vendor CSS Files -->
    <link
      href="{% static 'assets/vendor/quill/quill.snow.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/quill/quill.bubble.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/remixicon/remixicon.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/simple-datatables/style.css'  %}"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    />

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css ' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="wrapper">
      <!-- Sidebar  -->
      <nav id="sidebar">
        <div class="sidebar-header">
          <div>
            <a
              href="{% url 'homeinsightapp:profile-list' %}"
              class="logo d-flex align-items-center"
            >
              <img
                src="{% static 'assets/login/img/app_logo_white.png'  %}"
                alt=""
              />
              <span class="d-inline p-2 text-white"> {{ profile.name }} </span>
            </a>
          </div>
        </div>

        <ul class="list-unstyled components">
          <li class="active">
            <a
              href="{% url 'homeinsightapp:dashboard' profile_id=profile.uuid  %}"
              >Dashboard</a
            >
          </li>

          <li>
            <a
              href="{% url 'homeinsightapp:devicelist' profile_id=profile.uuid  %}"
              >Device manager</a
            >
          </li>
          <li>
            <a
              href="{% url 'homeinsightapp:devicelist' profile_id=profile.uuid  %}"
              data-toggle="collapse"
              aria-expanded="false"
              class="dropdown-toggle"
              >Devices</a
            >
            <ul class="list-unstyled" id="pageSubmenu">
              {% for device in devices %}
              <li>
                <a
                  href="{% url 'homeinsightapp:device-detail' profile_id=profile.uuid device_id=device.device_id %}"
                >
                  <span>{{ device.name }}</span>
                </a>
              </li>
              {% endfor %}
            </ul>
          </li>
        </ul>

        <ul class="list-unstyled CTAs">
          <li>
            <a
              href="https://www.anagaina.site/"
              target="_blank"
              class="download"
              >PORTFOLIO</a
            >
          </li>
          <li>
            <a href="{% url 'homeinsightapp:home' %}" class="article">HOME</a>
          </li>
        </ul>
      </nav>

      <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid">
            <div class="d-flex align-items-center gap-2">
              <div class="text-center">
                <button
                  type="button"
                  id="sidebarCollapse"
                  class="btn btn-outline-primary"
                >
                  <i class="fas fa-align-left"></i>
                </button>
              </div>

              <div class="col-auto">
                {% block pagetitle %} {% endblock pagetitle %}
              </div>
            </div>

            <div class="col-auto">
              <a
                role="button"
                class="btn btn-outline-primary"
                href="{% url 'homeinsightapp:profile-list' %}"
              >
                Profiles
              </a>
            </div>
          </div>
        </nav>

        <div class="row d-flex justify-content-between align-items-center">
          {% block content %} {% endblock content %}
        </div>
      </div>
    </div>
  </body>

  <!-- Vendor JS Files -->
  <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js'  %}"></script>

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"
  ></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
</html>

templates/profilecreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class=' min-h-screen flex-col flex justify-center items-center'>
    <div class="login">
        
        <h2 class="text-center font-medium text-5xl my-4 "> Create Profile  </h2>

        <form method="POST"  id="unitForm" data-localitati-url="/ajax/load-localitati/">
            {% csrf_token %}
            <table class="container input-text">
                {{ form.as_table }}
            </table>
            <div>
                <button type="submit" class="signin_button">Create Profile</button>
            </div>
        </form> 

        
            <a href="{% url 'homeinsightapp:profile-list' %}" type="button" class="cancel_button" >Cancel</a>
        
    </div>
</section> 






 

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
// get judet choice

$("#id_judet").change(function () {
        const url = $("#unitForm").attr("data-localitati-url");  
        const judetId = $(this).val();

        $.ajax({                       
            url: url,                    
            data: {
                'judet_id': judetId       
            },
            success: function (data) { 
                let html_data = '<option value="">---------</option>';
                data.forEach(function (localitate) {
                    html_data += `<option value="${localitate.id}">${localitate.name}</option>`
                });
                console.log(html_data);
                $("#id_localitate").html(html_data);
            }
        });

    });


</script>

{% endblock content %}

templates/profilelist.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section
  class="back h-full w-full min-h-screen flex-col flex justify-center items-center  p-4"
>
  <div class="login  p-4">
    <h1 class="h1">Profiles</h1>

    <div class="justify-center input_profiles">
      {% for profile in profiles %}
      <a href="{% url 'homeinsightapp:dashboard' profile_id=profile.uuid %}">
        <div
          class="w-32 h-32 m-4 bg-sky-500 rounded-md cursor-pointer justify-center items-center flex-col flex"
        >
          <p class="text-6xl" style="font-weight: 900">
            {{ profile.name|slice:":1" }}
          </p>
          <p>{{ profile.name }}</p>
        </div>
      </a>
      {% endfor %}
    </div>

    <div class="flex justify-center items-center">
      <a
        href="{% url 'homeinsightapp:profile-create' %}"
        class="btn btn-secondary btn-lg"
      >
        Add A New Profile
      </a>
    </div>
  </div>
</section>

{% endblock content %}

templates/temperature_study.html
{% block content %}

<div class="card info-card revenue-card">
  <div class="card-body">
    <h5 class="card-title">Temperature Study <span>| past 3 days </span></h5>

    <div id="areaChart"></div>

    <script>
      document.addEventListener("DOMContentLoaded", () => {
          new ApexCharts(document.querySelector("#areaChart"), {
          series: [{
              name: 'Temperature',
              data: [{% for temp in tempList %}  '{{ temp }}',  {% endfor %}] ,
          }],

          chart: {
              height: 300,
              type: 'area',
              toolbar: {
              show: false
              },
          },


          colors: ['#008ffb', '#2eca6a', '#ff771d'],

          fill: {
              type: "gradient",
              gradient: {
              shadeIntensity: 1,
              opacityFrom: 0.3,
              opacityTo: 0.4,
              stops: [0, 90, 100]
              }
          },

          dataLabels: {
              enabled: false
          },

          stroke: {
              curve: 'smooth',
              width: 2
          },

          xaxis: {
              type: 'datetime',
              categories: [{% for time in timeList %}  '{{ time }}',  {% endfor %}]
          },

          tooltip: {
              x: {
              format: 'dd/MM/yy HH:mm'
              },
          }

          }).render();

      });
    </script>
  </div>
</div>

{% endblock %}

templates/upload.html
{% block content %}

  <main id="main" class="main">


            
    <h5 class="card-title">Usage <span>/History</span></h5>

    


    <div class="card">
        <div class="card-body">
    
            <div class="card-title">
                <h5 class=" d-flex justify-content-between"> Import CSV  </h5>
            </div>
       
                    <!-- General Form Elements -->
                    <form  enctype="multipart/form-data"  method="post" >
                    {% csrf_token %}
                    {{ upload_form}}
                    <br/>
                    <input type="submit" value="Submit">
                    </form><!-- End General Form Elements -->

        </div>
    </div>





  </main><!-- End #main -->

  {% endblock content %}

templates/weather_widget.html
{% block content %}

<div class="card-body">
  <h5 class="card-title d-flex justify-content-between">
    {{profile.localitate}} <span> {% now "H:i" %} </span>
  </h5>

  <div class="d-flex flex-column text-center">
    <h5 class="display-5" style="color: #012970">{{ weather.temperature}}°C</h5>
    <div>
      <img src="http://openweathermap.org/img/wn/{{weather.icon}}@2x.png" />
    </div>
    <span class="small" style="color: #868b94">{{weather.description}}</span>
  </div>

  <div class="d-flex justify-content-center align-items-center">
    <div class="flex-grow-1 p-3 " style="font-size: 1rem">
      <div class="d-flex justify-content-center align-items-center">
        <i class="fas fa-wind fa-fw p-2" style="color: #868b94"></i>
        <span class="ms-1"> {{weather.wind}} m/s </span>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <i class="fas fa-tint fa-fw p-2" style="color: #868b94"></i>
        <span class="ms-1"> {{weather.humidity}} % </span>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <i class="fas fa-sun fa-fw p-2" style="color: #868b94"></i>
        <span class="ms-1"> {{weather.pressure}} hPa </span>
      </div>
    </div>
  </div>
</div>

{% endblock %}